# Generated by Django 4.2 on 2023-04-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaсancii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_vacancii', models.CharField(max_length=50, verbose_name='Наименование')),
                ('sphere', models.CharField(max_length=20, verbose_name='Сфера')),
                ('about_vacancii', models.TextField(blank=True, verbose_name='О вакансии')),
                ('time_create', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
